//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.03 at 10:25:11 AM IST 
//


package com.intimetec.crns.core.noaa;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import com.intimetec.crns.core.models.County2ZipMapping;


public class Feed {

    protected List<Feed.Entry> entry;
    
    /**
     *
     * Objects of the following type(s) are allowed in the list
     * {@link Feed.Entry }
     * 
     * 
     */
    public List<Feed.Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<Feed.Entry>();
        }
        return this.entry;
    }


    public static class Author {

        private String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

    public static class Entry {

        protected String id;
        protected Date published;
        protected Feed.Entry.Author author;
        protected String title;
        protected String summary;
        protected Date expires;
        protected Feed.Entry.Geocode geocode;
        protected Collection<County2ZipMapping> coutyMapping2Zip;
        
        public Collection<County2ZipMapping> getCoutyMapping2Zip() {
			return coutyMapping2Zip;
		}

		public void setCoutyMapping2Zip(Collection<County2ZipMapping> coutyMapping2Zip) {
			this.coutyMapping2Zip = coutyMapping2Zip;
		}

		public String toString(){
        	return "Entry {"
        			+"Id: "+id
        			+", published: "+published
        			+", author: "+author
        			+", title: "+title
        			+", summary: "+summary
        			+", expires: "+expires
        			+", geocode: "+geocode
        			+", County2ZipMapping: "+coutyMapping2Zip
        			+"}";
        }
 
        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * Gets the value of the published property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public Date getPublished() {
            return published;
        }

        /**
         * Sets the value of the published property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPublished(Date value) {
            this.published = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link Feed.Entry.Author }
         *     
         */
        public Feed.Entry.Author getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link Feed.Entry.Author }
         *     
         */
        public void setAuthor(Feed.Entry.Author value) {
            this.author = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }


        /**
         * Gets the value of the summary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSummary() {
            return summary;
        }

        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSummary(String value) {
            this.summary = value;
        }

        /**
         * Gets the value of the expires property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public Date getExpires() {
            return expires;
        }

        /**
         * Sets the value of the expires property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setExpires(Date value) {
            this.expires = value;
        }

        /**
         * Gets the value of the geocode property.
         * 
         * @return
         *     possible object is
         *     {@link Feed.Entry.Geocode }
         *     
         */
        public Feed.Entry.Geocode getGeocode() {
            return geocode;
        }

        /**
         * Sets the value of the geocode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Feed.Entry.Geocode }
         *     
         */
        public void setGeocode(Feed.Entry.Geocode value) {
            this.geocode = value;
        }

        public static class Author {

            protected String name;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }
            
            public String toString(){
            	return "Author {"
            			+"name: "+name
            			+"}";
            }

        }

        public static class Geocode {

            private String value;
            
            private List<String> geoCodes;
            
            public List<String> getGeoCodes() {
				return geoCodes;
			}

			public void setGeoCodes(List<String> geoCodes) {
				this.geoCodes = geoCodes;
			}

			public String getValue() {
                if (value == null) {
                    value = new String();
                }
                return this.value;
            }
            
            public void setValue(String value) {
                this.value = value;
            }
            
            public String toString(){
            	return "Geocode {"
            			+"value: "+value
            			+", geoCodes: "+geoCodes
            			+"}";
            }

        }
    }
    
    public String toString(){
    	return "Feed {"
    			+"Entries: "+entry
    			+"}";
    }
}
