//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.03 at 10:25:11 AM IST 
//


package com.intimetec.crns.core.noaa;

public class ObjectFactory {
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intimetec.crns.core.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Feed.Entry }
     * 
     */
    public Feed.Entry createFeedEntry() {
        return new Feed.Entry();
    }

    /**
     * Create an instance of {@link Feed.Author }
     * 
     */
    public Feed.Author createFeedAuthor() {
        return new Feed.Author();
    }

    /**
     * Create an instance of {@link Feed.Entry.Author }
     * 
     */
    public Feed.Entry.Author createFeedEntryAuthor() {
        return new Feed.Entry.Author();
    }

   /**
     * Create an instance of {@link Feed.Entry.Geocode }
     * 
     */
    public Feed.Entry.Geocode createFeedEntryGeocode() {
        return new Feed.Entry.Geocode();
    }
}
